server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/visitor?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      url: redis://localhost:6379   # 使用新命名空间 spring.data.redis
      password:
      client-type: lettuce          # 可选：lettuce 或 jedis

      lettuce:
        pool:
          max-active: 10            # 最大连接数
          max-idle: 10              # 最大空闲连接
          min-idle: 1               # 最小空闲连接
          max-wait: 2000ms          # 获取连接最大等待时间
          time-between-eviction-runs: 10s  # 连接池检测间隔

  mail:
    host: smtp.qq.com
    port: 587
    username: xx@qq.com
    password: xx
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.qianwang.pojo
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


qw:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: qianwanqqianwanqqianwanqqianwanqqianwanqqianwanq
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
